module.exports = {
	RECEIVE_MENU: 'RECEIVE_MENU',
  RECEIVE_CENTRES: 'RECEIVE_CENTRES',
  RECEIVE_STORES: 'RECEIVE_STORES',
  RECEIVE_PAGES: 'RECEIVE_PAGES',
  RECEIVE_SETTINGS: 'RECEIVE_SETTINGS',
  RECEIVE_SLIDERS: 'RECEIVE_SLIDERS',
  RECEIVE_NEWS: 'RECEIVE_NEWS',
  RECEIVE_ERROR: 'RECEIVE_ERROR',
  FILTER_STORES: 'FILTER_STORES',
  QUERIED: 'QUERIED',
  CLEAR_SEARCH: 'CLEAR_SEARCH',
  SHOW_SEARCH: 'SHOW_SEARCH',
  HIDE_SEARCH: 'HIDE_SEARCH',
  DROPDOWN_DOWN: 'DROPDOWN_DOWN',
  DROPDOWN_UP: 'DROPDOWN_UP'
};
